version: '3'
services:

  # 0verQuota
  app:
    image: node:8.12.0
    container_name: app_0verQuota
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html/0verQuota
    volumes:
      - ./app:/var/www/html/0verQuota/
    command: /bin/bash -c "npm install && npm run build && node"
    networks:
      - mynet

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx_0verQuota
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/log/nginx:/var/log/nginx
      - ./app:/var/www/html/0verQuota/
    networks:
      - mynet
    depends_on:
      - app


# Docker Networks
networks:
  mynet:
    driver: bridge

